# -*- coding: utf-8 -*-
"""task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YJIWPJtB7_5U1qJY9GzPY2xRZHvRch8d
"""

l = []
count_l = []
def flood_fill(lis,count) :
    for i in range(0,len(lis)) :
        if lis[i] == 'D' :
            count += 1 
        if lis[i] != '#' :
            for j in range(i+1,len(lis)) :
                if lis[j] == 'D' :
                    count += 1
            count_l.append(count)  
            return count_l   
        else : 
            break 
    
def total_D(d) :
    summ = 0 
    for i in d :
        summ += i 
    w.write(str(summ))



f = open('/content/input6_3.txt','r')
w = open('/content/output6_3.txt','w')
f1 = f.readline()
f2 = f1.split()
v = int(f2[0])
c = int(f2[1].strip())
dic = {}
for i in range(0,v) :
    f3 = f.readline().strip()
    a = flood_fill(f3,0)
total_D(a)


w.close()