# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GICdbfPid9s5VFJtUNbFve02Xpt-ymU3
"""

def job_schedule(task,call) :

    J_count = 0
    J_call = []
    j_count = 0
    overall = ''
    ct = 0 

    for i in call :
        if i == 'J' :
            J_call.append(task[ct])
            J_count += int(task[ct])
            overall += task[ct]
            ct += 1 
        elif i == 'j' :
            inp = J_call.pop()
            overall += inp
            j_count += int(inp)
    
    return overall, J_count, j_count 

f = open('/content/task3_input.txt','r')
f_w = open('/content/task3_output.txt','w')
n = f.readline().strip()
lis1 = sorted(f.readline().strip().split(' '))
lis2 = f.readline().strip()
total, J, j  = job_schedule(lis1,lis2)
f_w.write(f'{total} \nJack will work for {J} hours \nJill will work for {j} hours')
f_w.close()