# -*- coding: utf-8 -*-
"""task5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zkSX2DWIiqMNpPC0KE2b10_LZlhm2rXk
"""

def sort(arr) :

    name = []
    city = []
    time = []

    for i in range(0,int(arr)) :
        lis = f.readline().split()
        name.append(lis[0])
        city.append(lis[-3])
        time.append(lis[-1])

    for i in range(0,len(name)) :
        count = 0 
        for j in range(0,len(name)-i-1) :
            if name[j] > name[j+1] :
                name[j], name[j+1] = name[j+1], name[j]
                city[j], city[j+1] = city[j+1], city[j]
                time[j], time[j+1] = time[j+1], time[j]
                count += 1 
            if name[j] == name[j+1] :
                if time[j] < time[j+1] :
                    city[j], city[j+1] = city[j+1], city[j]
                    time[j], time[j+1] = time[j+1], time[j] 
                    count += 1 
        if count == 0 :
            break 

    for p in range(0,len(name)) :
        f2.write(f'{name[p]} will departure for {city[p]} at {time[p]} \n')
               
f = open('input5.txt','r')
f2 = open('output5.txt','w')
sort(f.readline())
f.close()
f2.close()