# -*- coding: utf-8 -*-
"""task4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TCabOtYeSP7xQvG0aJ0JfyHER1RUPrrt
"""

def sort(arr1,arr2) :

    for i in range(0,len(arr1)) :
        count = 0 
        for j in range(0,len(arr1)-i-1) :
            if arr2[j] < arr2[j+1] :
                arr2[j], arr2[j+1] = arr2[j+1], arr2[j]
                arr1[j], arr1[j+1] = arr1[j+1], arr1[j]
                count += 1 
            if arr2[j] == arr2[j+1] : 
                if arr1[j] > arr1[j+1] :
                    arr1[j], arr1[j+1] = arr1[j+1], arr1[j]
                    count += 1 
        if count == 0 :
            break 
    
    for k in range(0,len(arr1)) :
        f2.write(f'ID:{arr1[k]} Marks:{arr2[k]} \n')
    
f = open('input4.txt','r')
f2 = open('output4.txt','w')
f3 = f.readline()
sort((f.readline()).split(),(f.readline()).split())
f.close()
f2.close()