# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wEbECulPBBLbY4Jhrx-dplXrWZwStpi3
"""

#1a
f = open('input1a.txt','r')
f1 = f.readline()
f3 = open('output1a.txt','w')
for i in range(int(f1)) :
    f2 = f.readline()
    val = int(f2)
    if val%2 == 0 :
        f3.write(f'{val} is an Even number. \n')
    else :
        f3.write(f'{val} is an Odd number. \n')
f.close()
f3.close()

#1b 
f = open('input1b.txt','r')
f1 = f.readline()
f3 = open('output1b.txt','w')
for i in range(int(f1)) :
    f2 = f.readline()
    val = f2.split(' ')
    val2 = val[-1].split('\n')
    if val[2] == '+' :
        f3.write(f'The result of {val[1]} {val[2]} {str(val2[0])}  is  {str(int(val[1])+int(val2[0]))} \n')
    if val[2] == '-' :
        f3.write(f'The result of {val[1]} {val[2]} {str(val2[0])}  is  {str(int(val[1])-int(val2[0]))} \n')
    if val[2] == '*' :
        f3.write(f'The result of {val[1]} {val[2]} {str(val2[0])}  is  {str(int(val[1])*int(val2[0]))} \n')
    if val[2] == '/' :
        f3.write(f'The result of {val[1]} {val[2]} {str(val2[0])}  is  {str(int(val[1])/int(val2[0]))} \n')

f.close()
f3.close()