# -*- coding: utf-8 -*-
"""task3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wGNic5mymnhUSJNK-Nk6IaMKcdCkE7br
"""

def bubbleSort(arr):

    for i in range(len(arr)-1):
        count = 0  
        for j in range(len(arr)-i-1):
            if arr[j] > arr[j+1] :
                arr[j], arr[j+1] = arr[j+1], arr[j]
                count += 1
                f2.write(f'{arr[j]} ')
        if count == 0 :
            break 

                  
f = open('input3.txt','r')
f2 = open('output3.txt','w')
f1 = f.readline()
bubbleSort((f.readline()).split())
f.close()
f2.close()

# O(n) is obtained by using count variable. Here, the count variable is incremented if swapping occurs.
# If no swapping occurs which means the array is already sorted. The count variable remains 0 and breaks the outer loop.
# As a result, the code runs for n times to check whether there is any minimum value or not for the inner loop only.