# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZvmuF-4dFfF7u0DEYQGCygQaFxJzCEHJ
"""

def job_schedule(time,num) :

    dic = {}
    queue = []

    for i in range(0,num) :
        dic[i+1] = [time[i]]
        queue.append(time[i])

    ct = 0 
    for j in range(0,len(time)) :
        if [time[j]] not in dic.values() :
            if (time[j][1] >= queue[ct][0])  : 
                if time[j] not in dic[ct+1] : 
                    dic[ct+1].append(time[j])
                    queue.append(time[j])
                    ct += 1 
                else :
                    dic[ct+1].append(time[j])
    
    return len(queue)

def sort(sto) : 
    for i in range(len(sto)-1):
        count = 0  
        for j in range(len(sto)-i-1):
            if int(sto[j][1]) > int(sto[j+1][1]):
                sto[j][1], sto[j+1][1], sto[j][0], sto[j+1][0] = sto[j+1][1], sto[j][1], sto[j+1][0], sto[j][0]
                count += 1
        if count == 0 :
            break 
    return sto 

f = open('/content/task2_input.txt','r')
f_w = open('/content/task2_output.txt','w')

N,M = (f.readline().strip()).split()
N,M = int(N),int(M)
lis = []
for i in range(0,N) : 
    l = f.readline().strip().split()
    lis.append(l) 



f_w.write(str(job_schedule(sort(lis),M)))
f_w.close()