# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZZl01I7WiyoT9Y6VDBKgo2RaHgueH5tc
"""

import math 

def square(start,end) :

    lis = []

    for i in range(start,end+1) :
        st = math.sqrt(i)
        inp = str(st).split('.')
        if inp[1] == '0' :
            lis.append(st)

    return len(lis)

f = open('/content/task4_input.txt','r')
f_w = open('/content/task4_output.txt','w')
f = f.readlines()
for i in range(0,len(f)-1) :
    s,e = f[i].strip().split()
    out = square(int(s),int(e))
    f_w.write(f'{out} \n')
f_w.close()