# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SV2IvN0RXZj3tTCHoYXhGBrn2l9AzEkD
"""

def apply_BFS(dic,s) :
    color = [0]*(max(dic)+1)
    queue = []
    arr = []
    queue.append(s)
    color[s] = 1 
    while len(arr) < len(color)- 1  : 
        n = queue.pop(0)
        arr.append(n)
        for v in dic[n] :
            if color[v] == 0 :
                queue.append(v)
                color[v] = 1 
    
    print_arr(arr) 

def print_arr(lis) :
    store = ''
    for i in lis :
        store += str(i) + ' '
    w.write(store)
   
f = open('/content/input2_2.txt','r')
w = open('/content/output2_2.txt','w')
f1 = f.readline().split()
v = int(f1[0])
c = int(f1[1].strip())
dic = {}
for i in range(1,v+1) :
    if i not in dic :
        dic[i] = []

for j in range(0,c) :
    rd = f.readline().split()
    source,destin = int(rd[0]),int(rd[1])
    if (source in dic) and (destin not in dic[source]) :
        dic[source].append(destin)

for i,k in enumerate(dic.keys()) :
    if i == 0 :
       apply_BFS(dic,k)
w.close()