# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kTLhMmEhE0ievdOPhXRcGS12aNgLpCyr
"""

# Task 1A
import numpy as np 
f = open('/content/input1a_1.txt','r')
w = open('/content/output1a_1.txt','w')
f1 = f.readline()
f2 = f1.split()
v = int(f2[0])
c = int(f2[1].strip())
arr = np.zeros((v+1,v+1))

for i in range(0,c) :
    f3 = f.readline().split()
    a = int(f3[0])
    b = int(f3[1])
    c = int(f3[-1])
    arr[a,b] = c 

w.write(str(arr))
w.close()

# TASK 1B
g = open('/content/input1b_1.txt','r')
w = open('/content/output1b_1.txt','w')
g1 = g.readline()
g2 = g1.split()
v = int(g2[0])
c = int(g2[1].strip())
lis = []
dic = {}

for j in range(0,v+1) :
    if j not in dic :
        dic[j] = []

for i in range(0,c) :
    rd = (g.readline().strip()).split()
    source,destin,weight = int(rd[0]), int(rd[1]), int(rd[2])
    lis = destin,weight
    if (source in dic) and (lis not in dic[source]) :
        dic[source].append(lis)

for key,value in dic.items() :
    if len(value) < 1 :
        w.write(f'{key}: \n')
    else :
        store = ''
        for v in value :
            store += str(v) + ' '
        w.write(f'{key}: {store} \n')
w.close()