# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12GM9KxtxeYQkW2METqwf1wVkbhGb8rVc
"""

def dynamic_program(num,step) :

    if num == 0 :
        return step 
    else :
        return dynamic_program(num - (int(max(list(str(num))))),step+1)

f = open('/content/input1.txt','r')
f_w = open('/content/output1.txt','w')
inp = int(f.readline().strip())
min_step = dynamic_program(inp,0)
f_w.write(str(min_step))
f_w.close()