# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sAgv3dTky_DWbmMq6WFRfAF5MD8s3lyW
"""

def inp(num) :
    
    lis_1 = []

    for i in range(0,int(num)) :
        lis = (f.readline()).split()
        for j in range(0,len(lis)) :
            lis_1.append(int(lis[j]))
    
    n = merge_sort(lis_1,0,len(lis_1)-1)
    
    for k in range(0,len(n)) :
        f3.write(str(n[k])+' ')

def merge_sort(A,left,right) :

    if left < right :
        mid = (left+right)//2 
        merge_sort(A,left,mid)
        merge_sort(A,mid+1,right)
        merge(A,left,mid,right)
    return A 

def merge(A,left,mid,right) :

    n1 = mid - left + 1 
    n2 = right - mid 

    L = [0]*(n1)
    R = [0]*(n2)

    for i in range(0,n1) :
        L[i] = A[left+i]
    for j in range(0,n2) :
        R[j] = A[mid+j+1]
    
    i = 0
    j = 0
    k = left 

    while i < n1  and j < n2 :
        if L[i] < R[j]:
            A[k] = L[i]
            i += 1
        else :
            A[k] = R[j]
            j += 1
        k += 1

    while i < n1 :
        A[k] = L[i]
        i += 1
        k += 1 

    while j < n2 :
        A[k] = R[j]
        j += 1 
        k += 1 
    


f = open('input2.txt','r')
f2 = f.readline()
f3 = open('output2.txt','w')
inp(f2)