# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mq0YSLhlNEQi6uR9THM3ab8s3CeNtt91
"""

#Task 1 

def insertion(num) :

    lis_1 = []
    lis_2 = []
    dic = {}

    for i in range(0,int(num)) :
        lis1 = (f.readline()).split()
        lis2 = (f.readline()).split()
        for j in range(0,len(lis1)) :
            lis_1.append(int(lis1[j]))
            lis_2.append(int(lis2[j]))
    
    for k in range(0,len(lis_1)-1) :
        temp1 = lis_1[k+1]
        temp2 = lis_2[k+1]
        p = k 
        while k >= 0 :
            if lis_2[k] < temp2 :
                lis_1[k+1] = lis_1[k]
                lis_2[k+1] = lis_2[k]
            else :
                break 
            k -= 1 
        lis_1[k+1] = temp1
        lis_2[k+1] = temp2 

    
    for p in range(0,len(lis_1)) :
        f3.write(str(lis_1[p])+' ')

        

f = open('input1.txt','r')
f2 = f.readline()
f3 = open('output1.txt','w')
insertion(f2)